# Generated by Django 2.1.7 on 2019-03-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190301_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickets',
            options={'verbose_name': 'Bilet', 'verbose_name_plural': 'Biletlər'},
        ),
        migrations.AlterField(
            model_name='tickets',
            name='alici',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
